
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
  - host: {{ .Values.ingress.host }}{{.Values.global.url.host}}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port }}
